language: cpp
sudo: true
dist: trusty
script:
- |
  set -e -o pipefail
  export GIT_REVISION="$(git describe --tags --long --dirty --always)"
  docker build -t "spvcf:${GIT_REVISION}-tests" .
  docker run --rm "spvcf:${GIT_REVISION}-tests"
  docker run --rm -v $(pwd):/io "spvcf:${GIT_REVISION}-tests" cp spvcf /io
  ./spvcf -h
deploy:
  provider: releases
  api_key:
    secure: dJnEEwlcPE6hcs8xZcFM9pMYVzrFlk11CRkhahgvR7hh9rUGFjPFIMpmLUUQigKvf0YxgwZ5ZXcyOQfb0riRovN6K6xqsPU+V5csIHPr629LZIvklRzA0/163fUVm3BoYAA80LwwCjd+ysSS/Ot1PLE/BVbN6amYplFT5KiQVjn2l/P196/+NMeX1O3keGESlPdTu1L783PL3TOKTvT/J+XiX3PSwvMaasDRDB9Bbq4PzT7JNnO/s4XkT6zxHsKnM6bPzhmJ2yvmXJj3gBLgEQUS+BLh5vy2BkHsQgC3C5amtSpqtc2neifubU12BUHxypmoWndN8n0qkdLTEGOr/fvFthlnJ37rBJL9KWvBuDbYLH5DgO0XDXO7dN/WGSSh+fBkTBeWPkc3Sqrxk+Wg9CH+WRa2LTz6e/hmFyiSahI/g/6h8e7dS9A2o2dV4A+NVG4Zmj5TDojpd1FuwgRpcVD2urXjwJniYbZ+Ca30KRZDYjSmaatfs+J8Y7+CdzyZQIFR5z05Sy9xkKOmbAtx4esFNzHf/UfJj/4iqyw1/ZovZ0xNKWHJQ43dT7+YU7E0/HhQh1bKGO+7cO81Pz3DmzL9jFunOtumohucAW1gQRopVmlL+kJ5mc8HD1b56w7KlJEgFp4WWsEei/UvZeGSwGkgSG7p0lrRKss0A9d0zxs=
  file: spvcf
  on:
    repo: mlin/spVCF
    tags: true
  skip_cleanup: 'true'
